### ISSUE TITLE
Bug in 1.2.1

### ISSUE THREAD

**Issue by jedimonkey** [hupe1980/react-recaptcha-hook#16]
Looks like there is a bug in the latest 1.2.1 build - when I have upgraded to it I get the error:

./node_modules/react-recaptcha-hook/dist/react-recaptcha-hook.cjs.js
Module not found: Can't resolve '../../node_modules/@preconstruct/hook' in '/path/to/code/node_modules/react-recaptcha-hook/dist'

I backed up to 1.2.0 and things worked fine.

Upon looking at the code in 1.2.1 node_modules there is only 2 files in the dist folder:
react-recaptcha-hook.cjs.d.ts
react-recaptcha-hook.cjs.js

cat node_modules/react-recaptcha-hook/dist/react-recaptcha-hook.cjs.js
```
"use strict";
// this file might look strange and you might be wondering what it's for
// it's lets you import your source files by importing this entrypoint
// as you would import it if it was built with preconstruct build
// this file is slightly different to some others though
// it has a require hook which compiles your code with Babel
// this means that you don't have to set up @babel/register or anything like that
// but you can still require this module and it'll be compiled

// this bit of code imports the require hook and registers it
let unregister = require("../../node_modules/@preconstruct/hook").___internalHook(typeof __dirname === 'undefined' ? undefined : __dirname, "../..", "..");

// this re-exports the source file
module.exports = require("../src/index.tsx");

unregister();
```

whereas 1.2.0 has the following files:
react-recaptcha-hook.cjs.d.ts
react-recaptcha-hook.cjs.dev.js
react-recaptcha-hook.cjs.js
react-recaptcha-hook.cjs.prod.js
react-recaptcha-hook.esm.js

and the main js file swaps to dev/prod.

Was this just a bad build or is there meant to be more info?

**Comment by hupe1980** [comment]
Bug should be fixed in version 1.2.2
